# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='AssignIp',
            fields=[
                ('start_ip', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('end_ip', models.CharField(max_length=60)),
            ],
            options={
                'managed': False,
                'db_table': 'assign_ip',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assignment_no', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('publish_time', models.DateTimeField()),
                ('visibility', models.BooleanField()),
                ('helper_file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('helper_file', models.BinaryField(blank=True, null=True)),
                ('crib_deadline', models.DateTimeField()),
                ('num_problems', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Crib',
            fields=[
                ('crib_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('resolved', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'crib',
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('deadline_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('soft_deadline', models.DateTimeField()),
                ('hard_deadline', models.DateTimeField()),
                ('freezing_deadline', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'deadline',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('problem_no', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('helper_file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('helper_file', models.BinaryField(blank=True, null=True)),
                ('solution_filename', models.CharField(blank=True, max_length=50, null=True)),
                ('solution_file', models.BinaryField(blank=True, null=True)),
                ('compile_cmd', models.TextField(blank=True, null=True)),
                ('sol_visibility', models.BooleanField()),
                ('num_testcases', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'problem',
            },
        ),
        migrations.CreateModel(
            name='ResourceLimit',
            fields=[
                ('resource_limit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpu_time', models.IntegerField()),
                ('clock_time', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
                ('stack_limit', models.IntegerField()),
                ('open_files', models.IntegerField()),
                ('max_filesize', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'resource_limit',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sec_name', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('num_assignments', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('sub_no', models.IntegerField(primary_key=True, serialize=False)),
                ('marks_auto', models.IntegerField()),
                ('marks_inst', models.IntegerField()),
                ('sub_file_name', models.CharField(max_length=50)),
                ('sub_file', models.BinaryField()),
            ],
            options={
                'managed': False,
                'db_table': 'submission',
            },
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('testcase_no', models.IntegerField(primary_key=True, serialize=False)),
                ('infile_name', models.CharField(max_length=50)),
                ('infile', models.BinaryField()),
                ('outfile_name', models.CharField(max_length=50)),
                ('outfile', models.BinaryField()),
                ('marks', models.IntegerField()),
                ('visibility', models.BooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'testcase',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='SecUser',
            fields=[
                ('role', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sedb.User')),
            ],
            options={
                'managed': False,
                'db_table': 'sec_user',
            },
        ),
        migrations.CreateModel(
            name='UserSubmissions',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sedb.User')),
                ('num_submissions', models.IntegerField()),
                ('final_submission_no', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'user_submissions',
            },
        ),
    ]
