# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sedb', '0001_initial'),
    ]

    operations = [
    ]
